### ISSUE TITLE
Possible typo in cht.sh?

### ISSUE THREAD

**Issue by luckman212** [chubin/cheat.sh#107]
Sorry if I'm incorrect here, but I just tried installing **cht.sh** on macOS and ran into an issue. When trying to enter a language context from the shell, it does not switch. E.g.
```
$ cht.sh --shell
cht.sh> cd go
cht.sh>
```
However, running the following command _does_ work:
```
$ cht.sh --shell go
cht.sh/go>
```
After taking a look at the code, it seems the problem is with https://github.com/chubin/cheat.sh/blob/787c05d65190fab7a0c097e1167eaccffcaf6124/share/cht.sh.txt#L463
I believe the `$cmdargs` variable needs to be `$cmd_args`

After making this change, it started working as expected. Should I make a PR for this?

**Comment by chubin** [comment]
Yes, you are right, thank you very much for reporting! The problem is fixed
