### ISSUE TITLE
[CLI] Stealth mode shouldn't quit on lengthy queries

### ISSUE THREAD

**Issue by MahmoudDolah** [chubin/cheat.sh#115]
Hey, thanks a lot for building this amazing tool!
Stealth mode only allows queries that are 5 words long and when it goes over, it "ignores" and then quits out and brings you back to the main `cht.sh` shell

```
stealth: selection length is longer than 5 words; ignoring
cht.sh> 
```

I think it would be a better user experience to output the error message, but remain in stealth mode

**Comment by chubin** [comment]
Fixed, please test. (and thank you for reporting)
