### ISSUE TITLE
slsc cheat sheet

### ISSUE THREAD

**Issue by JensKorte** [chubin/cheat.sh#124]
# slsc is a spreadsheet calculator like sc

slsc [filename]

/ Menu
  cursor to move, return to select
  OR select by first letter

? Help (for further help see section help below)
  First letters of a topic+Enter are enough
  Enter to go back

mark region ends with CTRL+G (if you use dvtm, you may have to escape it with CTRL+G, CTRL+G)

Start a text/Enter in a field:
  < or > to align a text field to left or right
  = to enter a number or a formula
  TAB to edit the text of a cell
  Backspace (<-) do delete the cell content

The config file is ~/.slscrc

**Comment by chubin** [comment]
Fixed. Check: curl cheat.sh/slsc
