### ISSUE TITLE
XDG base directory support

### ISSUE THREAD

**Issue by weilbith** [chubin/cheat.sh#133]
Hey there!
Awesome tool! Especially with the editor integrations. :clap: 
I'm a big fan of the [XDG base directory standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). This `~/.cht.sh` folder kinda annoys me. Could we introduce a variable to configure for this like many [other programs](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Support) support as well?
Possibly this is already possible by defining some if the options within the configuration file. Unfortunately I didn't found a hint to that, but the code seems to be hard-coded.

**Comment by weilbith** [comment]
I'm just going through the list open issues by me.
I don't use `cheat.sh` anymore, so as nobody else seem to have further interest I just close it for the moment. Maybe it is even possible now and was forgotten. :shrug:

**Comment by abitrolly** [comment]
I don't think it is unreasonable to keep home dir clean of extra dirs. However, somebody needs to send a PR.
