### ISSUE TITLE
cht.sh gives 500 server error for rust/fn

### ISSUE THREAD

**Issue by sullivant** [chubin/cheat.sh#139]
Not sure if this is an issue with the server proper or with the formatting of the question but here is an example of a query that results in an internal server error:

http://cheat.sh/rust/fn

Additionally, from the command line curl gives the same error as does cht.sh's bash script.

**Comment by chubin** [comment]
@sullivant That is a very strange bug, I will take a look at it if it will persist in the new version, that is about to be deployed these days.

**Comment by chubin** [comment]
The new version is deployed. The bug can't be reproduced

@sullivant Thank you very much for reporting it. If you meet any bugs again, please report them immediately
