### ISSUE TITLE
Words like local, sh, $1, source, man, touch returning an HTTP 500 error.

### ISSUE THREAD

**Issue by sentientmachine** [chubin/cheat.sh#141]
**Summary:** Your nginx/1.13.12 isn't sanitizing some user input, and has a command injection vulnerability.  Your bash or gnu readline is intercepting user query strings in transit, and interpreting some of them.   I suggest you take everything offline until you find and eliminate this.  

Bash on the server side is interpreting my bash keywords and builtin variables like `local`, `sh`, `$1`, `source`, `man`, `touch` and others.  

**Reproduce:** 

Step 1: visit: http://cht.sh/bash/local
Step 2: get blasted in the face with a 500: `Internal Server Error The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

**Links that fail:**

1.  `http://cht.sh/sh/local`  fails as I said above.
2.  `http://cht.sh/bash/man` fails. 
2.  `http://cht.sh/bash/sh` also fails.
3.  `http://cht.sh/bash/$1` fails but 2 works fine, dollarsigns are being interpreted.  So it looks like bash doing the interpreting.

Relevant: https://xkcd.com/327 

Little bobby drop tables we call him...

**Comment by chubin** [comment]
@sentientmachine Thank you very much, for reporting it. Actually, it should not be a bug, not an active bug at least, but that's true, that there were several cache entries that such pages contained. I've refreshed the cache. Can you please check that now everything works fine for you?

**Comment by sentientmachine** [comment]
Your welcome, all the queries above are working again now.  Glad to hear it's not a bash command injection problem.

**Comment by chubin** [comment]
@sentientmachine Thank you very much, Eric!
