### ISSUE TITLE
Docker dockerfile bad reference

### ISSUE THREAD

**Issue by iomari** [chubin/cheat.sh#156]
Greetings,
I'm trying to configure self hosting.
The included Dockerfile references share/scripts/get-sheets.sh which doesn't exist which causes the docker build to fail after some minutes with:
sh: can't open 'share/scripts/get-sheets.sh': No such file or directory

Am I missing something?

thanks in advance
iomari

**Comment by Fake4d** [comment]
What was the solution? You directly closed this and i am running into the same problem..

**Comment by chubin** [comment]
It was not solved; I reopen this

**Comment by chubin** [comment]
@Fake4d The Dockerfile should be updated according to #98 
Please take a look at that issue

**Comment by abitrolly** [comment]
This issue with `Dockerfile` was fixed long ago, and the shell script was replaced with Python downloader.

https://github.com/chubin/cheat.sh/blob/a18e6d8089d154a374ed1f770577a53e1e635b2a/Dockerfile#L17

Open a new issue if you still have problems.
