### ISSUE TITLE
cheat.sh standalone mode + Python3

### ISSUE THREAD

**Issue by iomari** [chubin/cheat.sh#157]
Greetings,

What are the steps to use python 3 in standalone mode?
I've successfully converted to standalone mode using cht.sh --standalone-install
but it's using python 2.
Already pip is warning about using python 2.

iomari

**Comment by chubin** [comment]
@iomari 

cheat.sh itself supports both Python 2 and Python 3.
By default, cht.sh standalone installer uses Python 2.
That is how you can switch it to Python 3:

At the line 182 of `cht.sh` you have the following code:

```
  182   _say_what_i_do Creating virtual environment
  183   python2 "$(command -v virtualenv)" ve \
  184       || fatal Could not create virtual environment with "python2 $(command -v virtualenv) ve"
```

Replace here `python2` with `python3`, and rerun the script.

**Comment by iomari** [comment]
I did that but the screen output shows python2 references only.

**Comment by chubin** [comment]
@iomari Please add `-p python3` to the command line:
```
python3 "$(command -v virtualenv)" -p python3 ve
```

**Comment by iomari** [comment]
cool. it's working 😁

**Comment by iomari** [comment]
Spoke too soon.
It doesn't finish installing.
SyntaxError: Missing parentheses in call to 'print'. Did you mean
print("Done")?

Somewhere it's still using the print statement rather than the print
function that python 3 requires.
All tests failed.

**Comment by Konfekt** [comment]
Do these instructions still make standalone mode work after using rapidfuzz as merged in https://github.com/chubin/cheat.sh/pull/182 ?

**Comment by chubin** [comment]
@Konfekt Why are you asking? Do you suppose that rapidfuzz is not compatible with Python 3?

**Comment by Konfekt** [comment]
Dear @chubin, 

There used to show up some errors when using `cht.sh` in auto mode. Now it throws an error of a missing redis server on updating:

```
~/.local/share/cheat.sh/ve/bin/python ~/.local/share/cheat.sh/lib/fetch.py update-all
````

throws the error

```py
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
 
Does one have to run a redis server to update the cht.sh repositories?

**Comment by chubin** [comment]
@Konfekt you are right, rapidfuzz seems to support only python 3, so for python 2 we should fall back to fuzzywuzzy. I have fixed it now, and tested it with Python 2 (by the way, for the moment, the standalone installer uses python2 by default).

Please test.

Regarding caching, currently there are two caching types are supported: `redis` and `none`.
If you want to switch caching off and read the data directly from filesystem (what is ok,
if it is not a high loaded server), specify `none` as the cache type:

```
$ cat etc/config.yaml 
server:
    address: "0.0.0.0"
cache:
    type:   none
``` 

Does it work for you?

**Comment by Konfekt** [comment]
Yes, thank you, I can confirm that `~/.local/share/cheat.sh/ve/bin/python .local/share/cheat.sh/lib/fetch.py update-all` threw no error after chaning `type` in `~/.local/share/cheat.sh/etc/config.yaml` to `none`.

**Comment by chubin** [comment]
@Konfekt Thank you for testing; the standalone installer was fixed too

**Comment by chubin** [comment]
@maxbachmann Max, thank you for the heads-up; I believe that cheat.sh is already fully switched to Python 3, and Python 2 support should be fully dropped too; we should fix the documentation regarding this
