### ISSUE TITLE
cheat.sh standalone mode + Python3 continued

### ISSUE THREAD

**Issue by iomari** [chubin/cheat.sh#159]
Spoke too soon.
It doesn't finish installing.
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Done")?

Somewhere it's still using the print statement rather than the print function that python 3 requires.
All tests failed.

**Comment by chubin** [comment]
Please test, it should work now

**Comment by chubin** [comment]
But please update cht.sh first, or comment out the line `git checkout offline_usage` in your cht.sh client

**Comment by iomari** [comment]
Thanks. It's all good now. Installed and tested.
Thanks for your quick help.

iomari
