### ISSUE TITLE
History storage location

### ISSUE THREAD

**Issue by weilbith** [chubin/cheat.sh#161]
Hey there :wave: 
Having the environment variable `$CHTSH_CONF` I can change the location of my configuration. But apparently the location of the history file is fix coded to my `$HOME` directory. I would love to keep my users home folder clean. I could imagine to either add another variable like `$CHTSH_HIST` or (what I would favor) add a configuration option to specify the location.

**Comment by weilbith** [comment]
I'm just going through the list open issues by me.
I don't use `cheat.sh` anymore, so as nobody else seem to have further interest I just close it for the moment. Maybe it is even possible now and was forgotten. :shrug:

**Comment by abitrolly** [comment]
I am using it with `curl`, so I am not sure why the history file or how it is used, but I guess with #133 it may go into the same dir.
