### ISSUE TITLE
No longer work while getting help for a lot of bash commands

### ISSUE THREAD

**Issue by YorkZ** [chubin/cheat.sh#162]
It no longer works while trying to get the help for a lot of bash command. The following is just one of the many failed examples (some of the failed command are `tar`, `xargs` etc.)
```
$ curl https://cheat.sh/sed
[Adapter: cheat (Cheat)]:sed not found
```

**Comment by chubin** [comment]
@YorkZ Please test it. It should work now

**Comment by YorkZ** [comment]
Works now, wonderful!
