### ISSUE TITLE
Some queries (questions without answers) return no results

### ISSUE THREAD

**Issue by sentientmachine** [chubin/cheat.sh#164]
To reproduce issue visit: http://cht.sh/vim/return+outside+function

Error, no results: This is what is shown:

```
$ curl cheat.sh/
vim/return+outside+function
" Unknown cheat sheet.
" Please try to reformulate your query
```

I would expect to see one of these stackoverflow posts:
https://stackoverflow.com/search?tab=votes&q=%5bvim%5d%20return%20outside%20function

What is weird is that if I re-arrange the keywords, it works:

http://cht.sh/vim/function+return+outside

And I get a response as expected.  Why does the first query return nothing but the second query return a result?

**Comment by chubin** [comment]
@sentientmachine 

Hi Eric, thank you for reporting this; there are some cases where the index engine finds
irrelevant or sometimes even invalid answers. It's known, but now I see that it is worse that I thought,
as your example shows.

In this particular case, I've checked, what answer it was supposed to deliver, and I was really disappointed with the result. It is this question:

https://stackoverflow.com/questions/26818322/

In this case, there are no answers, so the answer makes perfectly sense, but of course, the search algorithm should be improved. As I mentioned, there are other known problems. In my opinion, the whole search engine should be rewritten. I hope to it this (2020) year. The new one should handle such cases correctly

**Comment by sentientmachine** [comment]
A question that has no answers shouldn't be selected for return to the user.  

Deep down in your code somewhere it should be an conditional to say: "And if there aren't any answers attached to this question, skip to the next one where there is an answer".  Still it's not a big deal.  vim and vimscript are fringe languages.

**Comment by chubin** [comment]
Yes, you are right, I hope this problem will be fixed in the next major update

**Comment by sentientmachine** [comment]
This appears to be fixed, I haven't seen any empty responses since Dec 2019.

**Comment by sentientmachine** [comment]
Sorry to touch this again, perl is another language heavily affected by this problem.  Now I'm seeing a similar problem same as the top with:

http://cheat.sh/perl/not+a+number
http://cheat.sh/perl/nan
http://cheat.sh/perl/not
http://cheat.sh/perl/number
http://cheat.sh/perl/foo
http://cheat.sh/perl/bin
http://cheat.sh/perl/avg
http://cheat.sh/perl/min

All of these return:

```
$ curl cheat.sh/perl/min
# Unknown cheat sheet.
# Please try to reformulate your query
```

It appears any cht search query for perl with 3 letters in it returns: `Unknown cheat sheet` 80% of the time.  Maybe because perl is a fringe language?

I expect to be presented one of the entries from say here:
https://stackoverflow.com/search?q=%5Bperl%5D+min
https://stackoverflow.com/search?q=%5Bperl%5D+avg

**Comment by chubin** [comment]
Yes, I can acknowledge this. I will investigate

**Comment by chubin** [comment]
The problem is fixed; please test, and thank you for reporting

**Comment by sentientmachine** [comment]
Thanks.  Fix confirmed.  Closing.
