### ISSUE TITLE
Cheat.sh plugin for Qt Creator IDE

### ISSUE THREAD

**Issue by pozemka** [chubin/cheat.sh#171]
I made a plugin for Qt Creator that provides easy access to cheat.sh.
If it is possible it will be great to list it in cheat.sh readme in "Editors integration section".

Plugin page https://github.com/pozemka/cheatsh-qtcreator (sources, examples and downloads)

Current features: 

- search word under cursor
- search selected
- query search
- disable comments
- paste answer (?TQ version)
- custom server URL
- custom search context (default is cpp)
- hotkeys and menu

**Comment by chubin** [comment]
@pozemka Wow! That's cool.

I want to add a link to it to README, but could you please make a short demo gif
with a query being processed?

**Comment by chubin** [comment]
I've found some gifs in your README, but maybe you could a new one for cheat.sh? Just a gif demonstrating the most important feature of the plugin?

**Comment by pozemka** [comment]
I've recorded new GIF. Hope it is not too large. Qt Creator's context menu doesn't fit in lower resolution.
GIF demonstrates how to search with plugin (context and query search) and how to paste result.
https://user-images.githubusercontent.com/1259724/73876361-ecce5d00-4867-11ea-9f75-c5b127a9739c.gif 784KiB
 
![cheatsh-qtcreator](https://user-images.githubusercontent.com/1259724/73876361-ecce5d00-4867-11ea-9f75-c5b127a9739c.gif)

**Comment by chubin** [comment]
Thank you for the cool gif!
I added a link to your plugin, see README.md.

Please check the table of the supported features,
is everything correct?

**Comment by pozemka** [comment]
Thank you. Did you forgot to update Contents?
Everything else looks correct.

When new features added I will let you know.

**Comment by chubin** [comment]
Hi @pozemka ! 
Do you still use your beautiful plugin?
I am going to publish it in twitter

**Comment by pozemka** [comment]
> 
> 
> Hi @pozemka !
> Do you still use your beautiful plugin?
> I am going to publish it in twitter

Hi. Yes.
Even updated it last week with the "previous/next answer" feature. Just forgot to mention it here.

**Comment by chubin** [comment]
Cool! I've just seen it in your readme file; it looks very cool; 
I am thinking about json format for the answer, that will contain
all possible answers, or maybe some portion of them (first 10 answers?).
Then it would be possible to go faster through them, or maybe
even add some sort of list or preview.

Another thing we are thinking about is some sort of live search and may by some possible
completions, à la google-suggest;

What do you think about these features? Would it be possible to map them to your plugin?

**Comment by pozemka** [comment]
I think to read answers from JSON in general should be simple enough. Qt has classes to work with JSON.

Unfortunately, I bumped into some restrictions for the answer format. It should be very simple form of HTML (HTML provided by cht.sh is a too heavy for basic Qt Creator HTML viewer). For now I am requesting ANSI version of answers from the server. Then ANSI codes are converted to the lightweight HTML on the client side.

However I understand that API should be designed for wide variety of users. And it is not very elegant to wrap ANSI-codes inside JSON. 

So probably answers in JSON could be plain text for preview. And then requested with desired formatting if needed.

Regardless live search. It would be cool challenge! One of the features I thought about was to have some kind of tab-completion similar to console client. At least for topics.

As I understand most of answers are come from StackOverflow (at least for me). Will live search for such questions? Or it will suggest only topics and answers from "repository"?

**Comment by chubin** [comment]
> HTML provided by cht.sh is a too heavy for basic Qt Creator HTML viewer

It is true. The html format of cheat.sh should be changed anyway. Currently it is just converted ANSI text, what makes little sense, because the text is formatted as markdown originally, and it is not a good idea to do this double conversion.

> So probably answers in JSON could be plain text for preview. And then requested with desired formatting if needed.

I think, ideally would be to specify the list of the needed format in the request

> As I understand most of answers are come from StackOverflow (at least for me)
> Will live search for such questions? Or it will suggest only topics and answers from "repository"?

Yes, ideally it would search in these questions too.
Currently we have several repositories attached, not only https://github.com/chubin/cheat.sheets but several others, including RosettaCode too (though support of RosettaCode is only preliminary);
but it would be great to search trough all kinds of the upstream repositories, incl. StackOverflow too
