### ISSUE TITLE
Add Ireaneus Linux cheatsheets repo

### ISSUE THREAD

**Issue by ireaneus** [chubin/cheat.sh#174]
Please add https://github.com/ireaneus/cheatsheet repo to this awesome program.  I will clean up my repo so it only holds cheatsheets, so the docker files and README.md will be removed.  

I have been using cheat for many years so I have populated several cheatsheets with my own examples.  I will continue to work on formatting and use the template you have specified.

Thank you, any questions feel free to contact me @ bwdave@protonmail.com
David.

**Comment by chubin** [comment]
David, how big is the intersections between your cheat sheets and the cheat sheets that we already have on cheat.sh? Have you already compared them somehow? Or not yet at all?

**Comment by ireaneus** [comment]
Yea, it could be pretty big.  I will create a repo with cheatsheets that your program doesn't already have, such as "ssh-google-auth" or "lvm disk management"  I will then submit that repo to you in a new issue.

**Comment by chubin** [comment]
It is ok if the pages are the same (the same names), but the content differs; it would be hard to check each repository for intersections, but if you know from the beginning that it is almost the same, then of course it is something completely different
