### ISSUE TITLE
TLS Certificate expired

### ISSUE THREAD

**Issue by mre** [chubin/cheat.sh#178]
I'm seeing some connection errors to cht.sh on [vscode-snippet](https://github.com/mre/vscode-snippet).
Looks like the certificate expired yesterday. See https://www.sslshopper.com/ssl-checker.html#hostname=https://cht.sh/.
Maybe we can renew it quickly? If not, I might want to switch to the http endpoint for the time being.

**Comment by ireaneus** [comment]
Yep, seeing the same thing here.

**Comment by chubin** [comment]
It should work now. Excuse me for the inconvenience.

**Comment by mre** [comment]
Works again here. Thanks for the quick fix! ❤️
