### ISSUE TITLE
Internal server error when requesting cht.sh/make/build

### ISSUE THREAD

**Issue by mre** [chubin/cheat.sh#179]
Getting an internal server error (500) when running the following request:

```
curl cht.sh/make/build
```

(Same for cheat.sh.)

**Comment by mre** [comment]
Same result via the browser, therefore changing the issue title accordingly.

**Comment by mre** [comment]
Think it's a problem with unknown topics.

```
curl cheat.sh/a # ok
curl cheat.sh/a/a # error
curl cheat.sh/a/b # ok
curl cheat.sh/foo # ok
curl cheat.sh/foo/bar # ok
curl cheat.sh/foo/x # error
```

The paths that work were maybe used for testing before and return "Unknown topic" as an answer.

**Comment by mre** [comment]
I assume that we throw an exception somewhere when we try to access an array or a map of topics and that one gets caught by the webserver and converted to a 500.
If that's true, you should be able to find a couple of log entries in the accesslog. 😉

**Comment by chubin** [comment]
It was a temporary redis outage; it was in a readonly state for a while; can you please test your queries now?

**Comment by mre** [comment]
Ah gotcha. Works perfectly now. 
I always wondered how cheat.sh was so fast. Redis is part of the answer, I guess. The work you did to make the service so fast would make for a very interesting talk I think.
Also, thanks again for the quick turnaround time. Simply amazing!

**Comment by chubin** [comment]
Thank you, Matthias; it uses multi layer caching, where redis is only a part of it;
I fully agree with you that caching is an important part of any modern piece of infrastructure,
and many developers underestimate it. It is a very interesting and important topic

**Comment by mre** [comment]
On that note, where do you host cheat.sh? I think the hosting provider is also pretty fast.
Sorry for completely hijacking this issue (which can be closed), but it was just too tempting to ask.

**Comment by chubin** [comment]
Hetzner datacenter, here in Bavaria; the servers are my own (configuration, tuning etc.).

**Comment by mre** [comment]
Nice! Moving all the things to Hetzner then. 😆 
Then again, I'm also in Germany so that could explain the latency...
Anyway, thanks for the input.

**Comment by chubin** [comment]
Hetzner is not bad indeed (very cheap, and the quality is pretty good).
Regarding latency, you are right; we should consider setting up several distributed replicas.

**Comment by mre** [comment]
You could consider using [now](https://zeit.co/) or [cloudflare workers](https://workers.cloudflare.com/). Super distributed edge-network and supports key-value stores. Just an idea, though as it requires quite a bit of work to get it done.

**Comment by chubin** [comment]
I should take a look at it. Thank your for the suggestion :+1:
