### ISSUE TITLE
Python returning no results for queries with %20 or whitespace.

### ISSUE THREAD

**Issue by sentientmachine** [chubin/cheat.sh#195]
Your service returns no results for multi keyword searches using spaces or %20 for python.

**Illustration:** About a month ago I ran this query through curl:

```
curl cht.sh/python/exponential%20backoff
#  Exponential backoff: time.sleep with random.randint(0, 1000)
# .... etc etc.
#  [NPE] [so/q/27438273] [cc by-sa 3.0] 
```

But now your service returns the error: `"Unknown cheat sheet"`
```
curl cht.sh/python/exponential%20backoff
#  Unknown cheat sheet.
#  Please try to reformulate your query

$ curl "cht.sh/python/exponential backoff"
#  Unknown cheat sheet.
#  Please try to reformulate your query
```
Looks like I have to use plus only, instead of spaces, like this to get a response:
```
$ curl cht.sh/python/exponential+backoff
#  Exponential backoff: time.sleep with random.randint(0, 1000)
# .... etc etc.
#  [NPE] [so/q/27438273] [cc by-sa 3.0] 
```

Same occurs with browser, clicky:  https://cheat.sh/python/exponential%20backoff

**More examples of what used to return a helpful response from last month, but is not working now:**

    curl "cht.sh/python/exists dictionary"
    curl "cht.sh/python/collapse+interior+spaces"
    curl "cht.sh/python/octal example"
    curl "cht.sh/python/deep copy"
    curl "cht.sh/python/flush stdout print"
    curl "cht.sh/python/lambda example"

clicky: 
https://cheat.sh/python/exists%20dictionary
https://cheat.sh/python/lambda%20example
https://cheat.sh/python/deep%20copy

All of these used to return a stackoverflow entry `exists%20dictionary` -> `so/q/1602934` but now it returns "Unknown cheat sheet."

It's been like this for the last 48 hours or more.  The mapping between `%20` literal space, and `+` seems to be messed up somewhere in transit.

**Comment by chubin** [comment]
Yes, I can acknowledge it. I will investigate

**Comment by sentientmachine** [comment]
Looks fixed.  You should put up a paypal donation button so I can throw some peanuts at you for the occasional swift kick of this amazing curl service.

**Comment by chubin** [comment]
@sentientmachine Eric say you for the potential donation :) But to say truth, your feedback and ideas is that what I appreciate even more! I am not actively working on the project at the moment, but I hope it will be better someday

**Comment by sentientmachine** [comment]
If the having of impact on the other side of the planet is where you derive motivation to keep going on this project, here is a gif to show you exactly how your curl service fits into my vim muscle memory command sequence:

[](https://i.imgur.com/5Mf1CZY.gif)

**Comment by chubin** [comment]
If I understood it right, for each cheat.sh query, a new tab in cheat.sh is automatically opened,
and you copy the answer from it. Ok.

My questions:

* can you handle things like comments (on/off)?
* is the language for the query (python in your case) automatically detected from your buffer configuration?

@dbeniamine what do you think, maybe you should add a new destination for the answer for the vim plugin? a tab? additionally to a buffer? I think it can be pretty convenient sometimes

**Comment by sentientmachine** [comment]
1. Yes vim calls curl cht.sh and the stdout goes to a new `~/.vim/cht/python/root+mean+squared+error.py`, makes a new tab like this `execute "tabedit " . the_filename` and inflicts a filetype like `execute "set ft=" . inflicted_filetype`.  
2.  So now the results of cht.sh can be navigated with normal navigation keys as I browse the stackoverflow answer.  I can highlight and copy lines to vim global register.
3.  Comments and cht parameters  Yes.  If I want to pass extra parameters like: "remove comments" or "give me the n'th answer" vim just hacks the query and looks for the parameters, pluck them off and put them back on in the curl cht.sh statement correctly.  See https://imgur.com/3zt4ZvQ
4.  Another way the editor "just knows" that files under the cht directory are python files (even when they're missing a .py extension or a shebang at the top) is this code:
```
   elseif whole_path =~ '.*/snippets/python/.*' || whole_path =~ '.*/cht/python/.*' || whole_path =~ '.*/usr/bin.*' 
         call PythonBothSetFiletypeSetup() 
     elseif whole_path =~ '.*/snippets/garpython36/.*' || whole_path =~ '.*/cht/garpython36/.*' 
         call PythonBothSetFiletypeSetup() 
```
These lines are in a function named: GuessFiletype() and run on every file that is ever opened in vim.  The vimscript8 peeks at the current directory and if it sees the file is in our cht history or a snippet history, it says aha, I know this is "python on windows vista/8.1" and not python 3.8, 3.6, 3.4, or 2.7 on gentoo.  It's a haaxxxx.  But that's how I like it.

I'm sure dbeniamine's plugin is perfect and great for normies, however it whisks me away to a new place, he can't know about how my muscle memory is set when I'm mid stream hacking away on a thing.  Muscle memory is encoded in the neuronal registers in my fingers and arms evolved to win slapping contests 800 million years ago.  Bram talks about how to encode programming skill in your registers in your arms rather than making the 8 foot network call journey to your head.

**Comment by dbeniamine** [comment]
@chubin : I am not sure to see what openning in a new tab will change from the buffer.

cheat.sh-vim already open in a vim buffer setting the filetype to the language if explicitly set in the request. From what I understand of @sentientmachine comment the main difference is that he have a hack to guess the programming language of the answer if not set in the query.

Am I missing something else ?

**Comment by chubin** [comment]
@dbeniamine David, the difference is minimal; just an additional option to make it possible (with some additional key combination) to open answer in a new tab instead of the buffer (just for tab-lovers). Nothing more

**Comment by dbeniamine** [comment]
Why not, I am oppening [an issue](https://gitlab.com/dbeniamine/cheat.sh-vim/-/issues/52) for this feature
