### ISSUE TITLE
cht.sh keeps changing without any change in its version number

### ISSUE THREAD

**Issue by simon04** [chubin/cheat.sh#196]
I'm packaging for AUR: https://aur.archlinux.org/packages/cht.sh/

The variables `__CHTSH_VERSION` and `__CHTSH_DATETIME` imply that the files are unchanged unless the version number is increased. However, `cht.sh.txt` has been changed multiple times w/o a change in the version/datetime variable – https://github.com/chubin/cheat.sh/commits/master/share/cht.sh.txt

And tag given commit with `cht@{version}`

**Comment by chubin** [comment]
Sorry for that. I will add a test, that would check that these variables are updated after each change of the file

**Comment by vladimyr** [comment]
Could you please also tag given commit with `cht@{version}` tag?
Lack of tagged `cht.sh` version is preventing me to package it for Homebrew: https://github.com/Homebrew/homebrew-core/pull/55078#pullrequestreview-416777028

**Comment by chubin** [comment]
@vladimyr yes, it is a good idea, accepted

**Comment by vladimyr** [comment]
Great, let me know if I can help you with that? I can write down a quick shell script to update in-file vars, commit a new version, and set a git tag?

**Comment by chubin** [comment]
@vladimyr Yes, it would be great, just go ahead

**Comment by vladimyr** [comment]
I've created a python script that can be used for tagging upcoming releases. Retroactive tagging of old ones can be done using the following snippet:
```bash
#!/bin/bash

for i in $(seq 1 6); do
	commit_id="$(git log --oneline -S__CHTSH_VERSION="$i" | tail -n1 | cut -d' ' -f1)"
	printf "git tag \"cht@%d\" %s -m \"cht: v%d\"\n" "$i" "$commit_id" "$i"
done
```
It will generate a series of git commands that create appropriate tags:
```sh
git tag "cht@1" 9886550 -m "cht: v1"
git tag "cht@2" e944172 -m "cht: v2"
git tag "cht@3" b3c9878 -m "cht: v3"
git tag "cht@4" 1125f13 -m "cht: v4"
git tag "cht@5" 884161c -m "cht: v5"
git tag "cht@6" 515c2c4 -m "cht: v6"
```

**Comment by jaklan** [comment]
@vladimyr if it's closed then maybe we can now try to add the tool to homebrew?

**Comment by vladimyr** [comment]
> @vladimyr if it's closed then maybe we can now try to add the tool to homebrew?

You won't get far with that one because cheat.sh still doesn't have any tagged releases https://github.com/chubin/cheat.sh/releases
