### ISSUE TITLE
Add zsh tab completion

### ISSUE THREAD

**Issue by gamehelp16** [chubin/cheat.sh#2]

**Comment by chubin** [comment]
Zsh support added by @johnnadratowski 

@nloomans @maximbaz @danielmanesku @dennise @Noammac @Chinggis6 @serycjon
@lepatrick714 @FilipBolt
Please test

**Comment by Noammac** [comment]
It seems to work with the normal instructions, but I'm trying to figure out
a way to load it via antigen. If anyone manages to do it, please share your
process.

**Comment by lawenda5** [comment]
Yes , I know all people try me help in computer, that for all thanks.

**Comment by chubin** [comment]
@Noammac If you manage to do via antigen, please share your solutions with us too.

**Comment by johnnadratowski** [comment]
Other option is to add it to oh-my-zsh.  I actually tested it using their
plugin system first. A large portion of zsh users use oh-my-zsh.

**Comment by Noammac** [comment]
If it's on oh-my-zsh it'll work with antigen

**Comment by Noammac** [comment]
You make a pull request, but I fear that may take some time as there are
currently 686 pending ones. Roby Russell is the sole centrepoint of the
project and as such he creates a very tight bottleneck for contribution to
oh-my-zsh. I would suggest working on a plugin that could be loaded
individually just for the sake of immediate usability. I'm currently
working on implementing it on antigen, the current method could be adapted
to other plugin managers (I reckon).

**Comment by chubin** [comment]
Perfect! And thank you very much for the explanation

**Comment by Noammac** [comment]
Managed to get it working on antigen. I copied the file to the directory `plugins/cht.sh` in my [dotfiles](gitlab.com/Noammac/dotfiles) repo. Then, in my .zshrc I put the line
```zsh
antigen bundle https://gitlab.com/noammac/dotfiles plugins/cht.sh
```
Now, as you can see from my commits, I made the mistake of calling the file `_cht.sh` which made antigen think that it's shell code that needs to be executed. That, evidently, is wrong. I renamed the file to `_cht-sh` and now everything works. I could open a new repo to support only this completion, but I think there may be an already existing repo (maybe @zsh-users'?) for compiling together command completion scripts.
