### ISSUE TITLE
Bring back foobar

### ISSUE THREAD

**Issue by ErezBinyamin** [chubin/cheat.sh#211]
When I first started using cheat.sh one of my favorite features was:
```bash
> curl cheat.sh/foo
```
I would get the pleasing response of:
```
bar
```
The current output is:  
```bash
> curl cheat.sh/foo

Unknown topic.
Do you mean one of these topics maybe?

    * fio 67
    * for 67
    * boot 57
```

"Some things are perfect just the way they are... I liked how things were, when they were"

**Comment by ErezBinyamin** [comment]
I would prefer to have the old functionality of ```curl cheat.sh/foo``` yielding ```bar```, but I would be equally happy with a print of the 2001 April fools [RFC](cheat.sh/rfc/3092)

**Comment by chubin** [comment]
Added, please test/edit

**Comment by ErezBinyamin** [comment]
Fantastic :)
