### ISSUE TITLE
html formating issue on website

### ISSUE THREAD

**Issue by FOSSBOSS** [chubin/cheat.sh#219]
looking at the website, [http://cheat.sh/man/ls](url)
there are 2 bogus formatting references to "kbd" elements. 
im not sure if this is a typo or if the kbd element is defined some place, but what displays is surely not desired.

**Comment by chubin** [comment]
Agree. It is a known issue, coming from the missing markdown interpreter (see #86).
I started working on this, but it is not finished yet.

I close this issue as a duplicate; please follow the markdown issue for updates
