### ISSUE TITLE
Am i trippin?

### ISSUE THREAD

**Issue by slump64** [chubin/cheat.sh#24]
![image](https://user-images.githubusercontent.com/14310552/41186212-78d61e92-6b9b-11e8-8d1f-ec0a57641887.png)

**Comment by slump64** [comment]
i mean this shouldn't be a mistake if it's all over the place, from the site itself to screenshot in readme

**Comment by chubin** [comment]
What is exactly the question?

Please try cht.sh or cheat.sh instead
```
curl cht.sh/ls
curl cheat.sh/ls
```

**Comment by slump64** [comment]
![image](https://user-images.githubusercontent.com/14310552/41189575-bc66d498-6bd8-11e8-90b2-84e258a107be.png)

**Comment by chubin** [comment]
@slump64 oops.. Indeed. Thank you very much! Fixed

**Comment by slump64** [comment]
it's still in the README picture

**Comment by chubin** [comment]
Will be fixed soon. README will be updated today (or tomorrow) and we will update the picture too
