### ISSUE TITLE
Replace ? with ^ for cht.sh options to avoid problems with shells

### ISSUE THREAD

**Issue by abitrolly** [chubin/cheat.sh#258]
Could it be that shell expansion is guilty of [ruined server tests](https://github.com/chubin/cheat.sh/runs/1397094457#step:6:26) in `master`?

```diff
Running 11: python/copy+file?Q          # [online]
curl -s http://localhost:8002/python/copy+file?Q
--- results/11	2020-11-13 17:34:54.220503401 +0000
+++ /tmp/cht.sh.tests-bT9l0Te0MBCja9	2020-11-13 17:38:24.817241135 +0000
@@ -1,3 +1,16 @@
+#  How do I copy a file in Python?
+#  
+#  shutil (http://docs.python.org/3/library/shutil.html) has many methods
+#  you can use. One of which is:
+
 from shutil import copyfile
 
 copyfile(src, dst)
+
```

`bash` and other shells expand `?` as any symbol, which creates problems for `cht.sh` `curl` commands.

    ✗ curl cht.sh/python/copy+file?QT 
    zsh: no matches found: cht.sh/python/copy+file?Q

Quoting helps.

    ✗ curl "cht.sh/python/copy+file?QT"
    zsh: no matches found: cht.sh/python/copy+file?Q

But there are still issues with processing the param.
```bash
✗ curl "cht.sh/python/copy+file\?QT"
from shutil import copyfile
copyfile(src, dst)
✗ curl "cht.sh/python/copy+file?QT" 
from shutil import copyfile

copyfile(src, dst)
```

I would propose replacing `?` with `^` to reduce the feeding grounds of quoting bugs. Why not other chars..

 * `!` used for some "shell signals"'
 * `#` in URL is not passed as GET request
 * `@` commonly used for revisions
 * `$` also used by shells
 * `%` used in [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters)
 * `&` used in URLs for params
 * `*` used by shells

**Comment by chubin** [comment]
Regarding test failures: I think, it is a bug indeed, and it has nothing to do with shell expansion in this case. It seems to be a caching issue. On sunday I started investigating it but didn't come to the end. Hopefully I'll do it today.

Regarding the `?` replacement: I can understand your arguments, but it should stay `?`.
In the console oriented web services we use the following URL -> CLI conversion:

* CLI options become URL argument;
* CLI arguments (not options) become the URL route;
* CLI command name becomes service name.

I.e.:
```
cht.sh -T ls
```
becomes:
```
cht.sh/ls?T
```

Using this conversion rules you can map any command line to any URL and back.
(the only exception is long options without values, i.e. `--help`. For such options
we have two possible mappings:

1. Argument without a value, i.e. `cht.sh --help` → `http://cht.sh?help=`
2. Or, more user-friendly, colon-form: `cht.sh --help` → `http://cht.sh/:help`

We can reserve the suggested `^` form for some other use cases.
