### ISSUE TITLE
where can I find all the snippets?

### ISSUE THREAD

**Issue by hyangrunning** [chubin/cheat.sh#270]
I prefere to get multiple results, not only the best match, when I search cht.sh go reverse a list.
Anyone could tell me how to find all the snippets ? 
Lots of thanks

**Comment by chubin** [comment]
Currently you can't get all snippets at once for coding question;
this feature will be added in future.
But what you can do, you can add `/1`, `/2` etc, to get alternative
answers:

```
curl cheat.sh/go/reverse+a+list/1
curl cheat.sh/go/reverse+a+list/2
```
