### ISSUE TITLE
Support Wayland (wl-copy in addition to xsel/pbcopy)

### ISSUE THREAD

**Issue by savchenko** [chubin/cheat.sh#271]
With a [number](https://fedoraproject.org/wiki/Changes/WaylandByDefaultForPlasma) of [various](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/rhel-8_0_0_release#desktop) [distributions](https://wiki.debian.org/NewInBuster) switching to Wayland as the default session, would it be possible to support `wl-copy` out of the box?

**Comment by chubin** [comment]
Yes, it is possible. We could even automatically check if it is Wayland or not, and chose the command based on that.

Could you please check what value of `$XDG_SESSION_TYPE` do you have?

**Comment by savchenko** [comment]
> Could you please check what value of $XDG_SESSION_TYPE do you have?

Sure:
```bash
$ systemctl --user show-environment | grep -i wayland
WAYLAND_DISPLAY=wayland-0
$ echo $XDG_SESSION_TYPE 
wayland

**Comment by chubin** [comment]
@savchenko Andrew, wayland support is implemented now; please test

**Comment by savchenko** [comment]
@chubin , will do, thanks!

**Comment by chubin** [comment]
@savchenko Have you tested it? Does it work for you?

**Comment by dotcs** [comment]
Thanks for adding wayland support. Much appreciated. Sad to see that @savchenko never answered the question, so I'll answert. I'm running on sway which uses the wayland protocol. I can confirm that version 0.4 of the script works for me! 🥳

More info if needed:
```console
$ echo $XDG_SESSION_TYPE
wayland
$ pacman -Si sway | grep -i version
Version         : 1:1.7-2
$ pacman -Si $(pkgfile wl-copy) | grep -i version
Version         : 1:2.1.0-1
```

**Comment by abitrolly** [comment]
@dotcs thanks for validating. Closing as fixed then.
