### ISSUE TITLE
Invoke-WebRequest through powershell returns HTML instead of a terminal friendly response

### ISSUE THREAD

**Issue by gargakshit** [chubin/cheat.sh#273]
Steps to reproduce:

- Run `(Invoke-WebRequest -Uri https://cheat.sh).Content` in powershell

Workaround

- Add the "curl" user agent to Invoke-WebRequest as `(Invoke-WebRequest -Headers @{"User-Agent" = "curl/2.0"} -Uri https://cheat.sh).Content`

In the new windows terminal, all the ANSI escape sequences are rendered correctly, so I guess returning a terminal friendly response when using a powershell U-A should make sense.

Screenshot when using the workaround:
![image](https://user-images.githubusercontent.com/15605299/104021821-72c7f600-51e5-11eb-980d-0c16bad560c2.png)

**Comment by chubin** [comment]
Fixed, please test

**Comment by gargakshit** [comment]
Yup its fixed. Thank you!
