### ISSUE TITLE
Docker self hosted version shows control characters instead of colors

### ISSUE THREAD

**Issue by mcallaway** [chubin/cheat.sh#274]
This is on Mac 10.15.7 with Docker for Mac:

    > docker --version
    Docker version 20.10.0, build 7287ab3

When using the docker-compose version of cheat.sh:

    > git log | head -n1
    commit 4d86f0fb959b92e4dfeb141ddd0f6424322d131c

I do:

    > docker-compose up --build

Things build without error and start up:

    Successfully built 56154e635c2a
    Successfully tagged cheat.sh:latest
    Starting cheatsh_redis_1 ... done
    Starting chtsh           ... done
    Attaching to cheatsh_redis_1, chtsh
    redis_1  | 1:C 10 Jan 17:59:13.308 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
    redis_1  | 1:C 10 Jan 17:59:13.308 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
    redis_1  | 1:C 10 Jan 17:59:13.308 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
    redis_1  | 1:M 10 Jan 17:59:13.309 * Running mode=standalone, port=6379.
    redis_1  | 1:M 10 Jan 17:59:13.309 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
    redis_1  | 1:M 10 Jan 17:59:13.309 # Server initialized
    redis_1  | 1:M 10 Jan 17:59:13.309 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
    redis_1  | 1:M 10 Jan 17:59:13.310 * DB loaded from disk: 0.000 seconds
    redis_1  | 1:M 10 Jan 17:59:13.310 * Ready to accept connections
    chtsh    | Starting gevent server on 0.0.0.0:8002
    chtsh    | 172.19.0.1 - - [2021-01-10 17:59:19] "GET / HTTP/1.1" 200 448540 0.246588
    chtsh    | 172.19.0.1 - - [2021-01-10 17:59:19] "GET /files/opensearch.xml HTTP/1.1" 200 986 0.001436

But when I point my browser to localhost:8002 I see:

<img width="1275" alt="Screen Shot 2021-01-10 at 11 59 30 AM" src="https://user-images.githubusercontent.com/517288/104131383-9c933100-533b-11eb-88a5-c193b29d95df.png">

**Comment by abitrolly** [comment]
Yes. Nobody knows what cause it yet. The primary goal was to make it running in Docker.

**Comment by chubin** [comment]
I believe it works now

**Comment by aamehedi** [comment]
I am facing this same issue now.

```
> docker --version
Docker version 20.10.10, build b485636f4b
```
```
> git log | head -n1
commit 609c79093d629524f220cabf75d05a9e92135816
```

**Comment by abitrolly** [comment]
So far I traced it to https://github.com/chubin/cheat.sh/blob/609c79093d629524f220cabf75d05a9e92135816/lib/frontend/html.py#L36

[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5iaW4vc3J2LnB5LT4-Z2V2ZW50LnB5d3NnaTogcGF0Y2hfYWxsKClcbmdldmVudC5weXdzZ2ktPj5hcHAuYW5zd2VyOiAvcGF0aDp0b3BpY1xuI2xvb3AgSGVhbHRoY2hlY2tcbiMgICAgSm9obi0-PkpvaG46IEZpZ2h0IGFnYWluc3QgaHlwb2Nob25kcmlhXG4jZW5kXG4jTm90ZSByaWdodCBvZiBKb2huOiBSYXRpb25hbCB0aG91Z2h0cyFcbmFwcC5hbnN3ZXItLT4-Y2hlYXRfd3JhcHBlcjogcXVlcnksIGZvcm1hdFxuY2hlYXRfd3JhcHBlci0tPj5mcm9udGVkLmh0bWwudmlzdWFsaXplOiBhbnN3ZXJfZGF0YSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5iaW4vc3J2LnB5LT4-Z2V2ZW50LnB5d3NnaTogcGF0Y2hfYWxsKClcbmdldmVudC5weXdzZ2ktPj5hcHAuYW5zd2VyOiAvcGF0aDp0b3BpY1xuI2xvb3AgSGVhbHRoY2hlY2tcbiMgICAgSm9obi0-PkpvaG46IEZpZ2h0IGFnYWluc3QgaHlwb2Nob25kcmlhXG4jZW5kXG4jTm90ZSByaWdodCBvZiBKb2huOiBSYXRpb25hbCB0aG91Z2h0cyFcbmFwcC5hbnN3ZXItLT4-Y2hlYXRfd3JhcHBlcjogcXVlcnksIGZvcm1hdFxuY2hlYXRfd3JhcHBlci0tPj5mcm9udGVkLmh0bWwudmlzdWFsaXplOiBhbnN3ZXJfZGF0YSIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

**Comment by abitrolly** [comment]
Found the problem. Apline by default comes with limited BusyBox version of `sed` which doesn't process `ansi2html` rules correctly.

I submitted a patch https://github.com/pixelb/scripts/pull/30 to warn about it.

Testing a fix now.

**Comment by abitrolly** [comment]
@mcallaway @aamehedi this is now fixed.

**Comment by aamehedi** [comment]
@abitrolly Thanks a lot. It works!

**Comment by mcallaway** [comment]
- - 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
