### ISSUE TITLE
Use long options too, to support "Tutoring — It should help you to learn the subject."

### ISSUE THREAD

**Issue by ElijahLynn** [chubin/cheat.sh#275]
Long options are self-documenting and help greatly with learning. Per the goal of:
> Tutoring — It should help you to learn the subject.

in the README.md file, I recommend that all cheatsheets include the GNU Long Options when available. 

I tried with cht.sh/grep and didn't see any long options so not sure if other cheatsheets are already doing this.

**Comment by chubin** [comment]
Thank you! We will keep this in mind
