### ISSUE TITLE
Database of the project

### ISSUE THREAD

**Issue by Dj-Polyester** [chubin/cheat.sh#284]
Is there any way you could make the database available? My project uses [`cht.sh`](cht.sh). In a single page I show a number (say 5) entries for a query. For each page I need to renew the entries. Currently, I send a get request for each entry, then I parse them to my needs. Parsing is OK, but sending requests take too long, even in parallel (mine took about 2 secs for 3 entries for a page). I can make the repo available on request. Thanks. 

**NOTE:** I only would like to have the entries of course, not the secret stuff (e.g. [this](https://cht.sh/python/dijktra/3) is an entry)

**Comment by chubin** [comment]
@Dj-Polyester Batuhan hi! Yes, you can have some of the entries (see the "standalone" issue for that). Unfortunately, not yet all of them: pages that are generated on the fly can't be fetched up-front.
There are some potential optimizations though, the could be helpful. Ping me if you still have interest to the project

**Comment by Dj-Polyester** [comment]
@chubin Thank you for the reply. I decided to go for fetch API, and cache the data in a local Postgres server. For repeated access, it works fine; however, for the first time, requesting takes a while (5-10 secs for my connection). Thank you for the suggestion! I will look into that standalone part. If you have any other suggestions, you can reply in [#292](https://github.com/chubin/cheat.sh/issues/292). I demonstrate my project there crediting your work.
