### ISSUE TITLE
Lynx reports "** Bad HTML!! Use -trace to diagnose. **"

### ISSUE THREAD

**Issue by btdmaster** [chubin/cheat.sh#288]
Lynx.trace file:
```
SGML: *** Unknown element "datalist"
SGML: Attribute value topics ***ignored
SGML: found attribute value, 0
SGML: attribute value is '7z'
SGML: Still open FORM 	<- ***invalid start <OPTION>
SGML: Start <OPTION>
Bad HTML: OPTION tag not within SELECT tag
```
and so on for every suggestion. Should be fixed by wrapping all options (from 7z to zypper) with a select tag.

**Comment by abitrolly** [comment]
@btdmaster it is already wrapped in a [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) and https://validator.w3.org/nu/ doesn't complain about that.

**Comment by btdmaster** [comment]
Makes sense. Closing.
