### ISSUE TITLE
https://cht.sh/:cht.sh returning older version (regression)

### ISSUE THREAD

**Issue by luckman212** [chubin/cheat.sh#290]
`curl https://cht.sh/:cht.sh` is returning a very old and seemingly regressed version of the script. Can someone please check?

version as of yesterday:
```
__CHTSH_DATETIME="2020-08-05 09:30:30 +0200"
```
version that is being served as of this writing:
```
__CHTSH_DATETIME="2018-07-08 22:26:46 +0200"
```

**Comment by abitrolly** [comment]
Only @chubin himself can check the mighty server.

**Comment by sentientmachine** [comment]
Also another clue, all non-cached queries are going out and coming back with: "Unknown cheat sheet".  This happens every 4 +- 1 months.

**Comment by chubin** [comment]
Sorry guys, my bad; it was an old version running indeed

@sentientmachine Eric, the problem that you are referring too was fixed a couple of months ago; now errors are cached, but if you remember your queries we can clean the cache too
