### ISSUE TITLE
Unable to install on Mac Big Sur v11.3

### ISSUE THREAD

**Issue by CharlieDixon** [chubin/cheat.sh#294]
I've followed the installation instructions for both the user installation and the global installation but neither method seems to work. When I try to install using the global method I get `suspended (tty input)  sudo tee/usr/local/bin/cht.sh` and the cht.sh command is not recognised. Has anyone managed to get this running on Big Sur and if so how?

**Comment by chubin** [comment]
How exactly are you installing it? What is the command?
Do you want to install the client or the server?

**Comment by SnoXJaeX** [comment]
this guy is robbing me and your helping 

 

    On Saturday, May 1, 2021, 06:33:36 AM CDT, Igor Chubin ***@***.***> wrote:  
 
 


How exactly are you installing it? What is the command?
Do you want to install the client or the server?

**Comment by chubin** [comment]
I didn't understand the last comment

**Comment by demostanis** [comment]
You're probably missing a space between `sudo tee` and `/usr/local/bin/cht.sh`.

**Comment by CharlieDixon** [comment]
Feeling like quite the dufus now, realised that because I'm running a zsh terminal cht.sh presumably isn't automatically added as an alias as there isn't a bash profile. 
On mac you can run the script from the folder using `sh cht.sh` or `./cht.sh`. Alternatively, you can just add an alias of your own to the .zshrc dotfile e.g. `alias cht.sh="~/path-to-dir/cht.sh"`. Hope that helps anyone else out if they're also new to zsh and macOS.
