### ISSUE TITLE
Add fish tab completion

### ISSUE THREAD

**Issue by chubin** [chubin/cheat.sh#3]

**Comment by Dagefoerde** [comment]
https://github.com/Dagefoerde/dotfiles/blob/fc5452bb9931f20d5702b2d5a25904da71a0c9ef/fish/own_functions/cheat.fish#L7 :)

**Comment by chubin** [comment]
@tobiasreischmann @Dagefoerde Thank you very much! Now we hash fish

The list of completions is expanded at the moment, when the function is executed, correct?
How would you change it if you want to generate the completion list on the fly?
Is it a good idea at all, what do you think? (probably not, because the list of topics changes not so often)
