### ISSUE TITLE
Noncached answers, returning 500 internal server error.

### ISSUE THREAD

**Issue by sentientmachine** [chubin/cheat.sh#300]
This link produces a 500 internal server error:
http://cheat.sh/psql/convert+numeric+column+to+integer

Wheras this works as expected:
http://cheat.sh/python/write+to+file

Again this produces a 500 internal server error:
http://cheat.sh/python/write+to+foobar

screenshots
https://i.imgur.com/ON0X66o.png
https://i.imgur.com/q4C5T2z.png

Why is your server showing me variables that link to brightcove and something.oreilly.com and techbus.safaribooks, to fetch courses then blasting me in the face with "The hostname changed, so you can't do that."

**_Caution, Rogued Robots?_**

https://youtu.be/iHwIFGi3WPU?t=112

**Comment by chubin** [comment]
Please try now.

What is for JS code? We have no JS in the project

**Comment by sentientmachine** [comment]
It's working now.  The brightcove and techbus errors were clientside cascade errors from a naughty browser plugin that was examining your web page, and when it tried to talk to its mothership server, it caused a cascade of errors.  today I learned.

Another gentle reminder for everyone everywhere to review all browser plugins that can examine site data, they can and will examine your visited-site data and transmit observed information back to its `whatever.mothership_data_collector49783.com` then puke on the carpet when the original site produces a malformed response during chrome V8 engine html/javascript render.

Thanks.

**Comment by chubin** [comment]
Now it makes sense. Eric, thank you for reporting!

**Comment by sentientmachine** [comment]
Reopening because this bug crops up every 2 to 5 months.

This query works because serverside has cached the response:
http://cheat.sh/psql/convert+numeric+column+to+integer

This query produces an internal server error because serverside has not cached the response:
http://cheat.sh/psql/convert+numeric+column+to+double
