### ISSUE TITLE
Strange output in main page on self-hosted 

### ISSUE THREAD

**Issue by Galphaa** [chubin/cheat.sh#301]
Hello, used compose to setup selfhosted version and got this strange output on main page 

![image](https://user-images.githubusercontent.com/17854037/125821978-f08b2740-4a52-4a6c-a47c-3cee751d80ec.png)

**Comment by ErezBinyamin** [comment]
Duplicate of #274

**Comment by abitrolly** [comment]
If it still not solved, then maybe https://github.com/ionelmc/python-hunter can help to trace down what is wrong. Maybe headers, or maybe ANSI converter doesn't work.

**Comment by abitrolly** [comment]
Fixed in #316. Please check.
