### ISSUE TITLE
[cht.sh] cert expired

### ISSUE THREAD

**Issue by rprimus** [chubin/cheat.sh#306]
Sun Sep 19 11:37:50 BST 2021

Hi,

Just letting you know the cert on `cht.sh` has expired at:

> Sun, 19 Sep 2021 09:21:23 GMT

Regards,

**Comment by chubin** [comment]
Should be already fixed; please check

**Comment by rprimus** [comment]
Sun Sep 19 17:59:35 BST 2021

@chubin - verified: both for `cht.sh` and `cheat.sh`

Cheers!
