### ISSUE TITLE
How do i look for "g++" ?

### ISSUE THREAD

**Issue by LamprosPitsillos** [chubin/cheat.sh#308]
` curl -s cheat.sh/:list `
shows that there is data for `g++`.
```
curl -s cheat.sh/g\+\+
curl -s cheat.sh/g++
```
Don't seem to find it.

**Comment by Jan200101** [comment]
Putting quotes around it does not help, this seems to be a problem with how plus symbols are used within URLs
[cheat.sh/g++](http://cheat.sh/g++) opening this in your browser brings you to cheat.sh/g/+ instead
