### ISSUE TITLE
typo in URL in README image

### ISSUE THREAD

**Issue by sparecycles** [chubin/cheat.sh#31]
The first (colored) URL is currently `chteat.sh` but should be `cheat.sh`:

![screen shot 2018-07-10 at 11 45 33 pm](https://user-images.githubusercontent.com/719818/42554890-5f351d80-849b-11e8-96ec-f80bf62520a3.png)

**Comment by chubin** [comment]
Yes, it was already reported. It will be fixed today.

**Comment by chubin** [comment]
Fixed. Thank you fo reporting
