### ISSUE TITLE
https certificate expired

### ISSUE THREAD

**Issue by ngaro** [chubin/cheat.sh#321]
The certificate of https://cht.sh expired a couple of hours ago

I noticed that you are using Nginx with Let's Encrpt certificates.

I strongly suggest to use the docker container `jonasal/nginx-certbot` (you can just pull it from dockerhub)

This will give you a nginx that automatically renews it's certificates before they expire.
See https://github.com/JonasAlfredsson/docker-nginx-certbot for full info

**Comment by chubin** [comment]
Thank you
