### ISSUE TITLE
When i edit/add something to some cheatsheet, I wish I could search the things I edited/added even though my pull request is not merged? Is is possible?

### ISSUE THREAD

**Issue by AstroShen** [chubin/cheat.sh#329]

**Comment by AstroShen** [comment]
Sometimes I don't care whether my editings will be merged, just for personal use. That means I want to build my own cheatsheet based on cheat.sh by adding something missed on cheat.sh

**Comment by abitrolly** [comment]
Yes, it is possible. This script fetches repos. You want to patch or config it to fetch edited cheatsheets from your location.

https://github.com/chubin/cheat.sh/blob/46d1a5f73c6b88da15d809154245dbf234e9479e/Dockerfile#L14-L16

**Comment by chubin** [comment]
It is possible but only if you use your own installation. cheat.sh itself uses the master branches of all upstream repos
