### ISSUE TITLE
cht.sh and cheat.sh are down

### ISSUE THREAD

**Issue by colbin8r** [chubin/cheat.sh#335]
Getting 500 Internal Server Errors when using cheat.sh - browsing to http://cht.sh/ returns:

> # Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by n0ks** [comment]
Same here :/

**Comment by chubin** [comment]
Should be back online; please retest

**Comment by colbin8r** [comment]
Back for me! Thanks @chubin - and thanks for this wonderful service. I use it all day every day!
