### ISSUE TITLE
Name conflict with Cheat, this project already exists...

### ISSUE THREAD

**Issue by pirate** [chubin/cheat.sh#34]
https://github.com/chrisallenlane/cheat

This project has existed for years and has a big following, among others like https://github.com/hubsmoke/bro and https://github.com/tldr-pages/tldr.

Please strongly consider changing the name so as not to conflict with the existing project that had it first.

**Comment by chubin** [comment]
We are of course aware of the beautiful `cheat` project and we even use it (what is documented in our README.md file), but please keep in mind that:

1. Our project is called `cheat.sh` and not `cheat` (for example `xterm.js` and `xterm` are two separated projects and `xterm` existed for decades before `xterm.js`; should they be renamed too from your point of view?);
2. We are trying to mitigate the impact by using `cht.sh` where possible;
3. We do not and did not ever use the name to steal, to borrow, or to somehow use popularity of `cheat`.

I do not see any naming conflct actually. The client/command is called `cht.sh`, does not even have `cheat` in their name.

I am a big fan of the `cheat` project myself, and I don't want to do any harm for it. Even more, as I said, I would prefer that we cooperate with that project.

**Comment by chubin** [comment]
I think that this issue can be closed now. I've contacted @chrisallenlane with cooperation proposals. If there will be any updates, I will keep you posted

**Comment by chubin** [comment]
Email from Chris Allen Lane (@chrisallenlane) regarding the name controversy:

```

Hi, Igor

Thanks for reaching out to me.

Somehow I hadn't heard of cheat.sh before, but it's a hugely impressive
project. Thanks for bringing it to my attention!

Regarding your questions:

> 1. Because I wanted to thank you for your project and for
the cheat sheets you created;

My pleasure. Likewise, thanks for your work with cheat.sh.

> 2. Because of the name controversy;

Don't worry about it. "Namespace conflicts" like this are inevitable
from time to time, and, like you said, `cheat.sh` and `cheat` are
dissimilar enough to be distinguishable regardless.

[...]

Thanks.

Chris Allen Lane


```

**Comment by chrisallenlane** [comment]
Yep - there's no problem here, in my mind. Thanks, guys.
