### ISSUE TITLE
Add language: Robot Framework

### ISSUE THREAD

**Issue by kalyncoose** [chubin/cheat.sh#341]
Hello, I'd like to help contribute and add the [Robot Framework](https://robotframework.org) language. Should I start by creating a monorepo for RobotFramework cheats? I think Robot Framework could be added using the Prefix `rf/` since `robotframework/` is too long. Additionally, there are [6,000+](https://stackoverflow.com/questions/tagged/robotframework) questions in StackOverflow with the tag `[robotframework]`. I did read the README and CONTRIBUTING file, I am just wondering what the current preference is on how to contribute since I read this quote:

> Instead of creating yet another mediocre cheat sheet repository, we are concentrating our efforts on creation of a unified mechanism to access selected existing well developed and good maintained cheat sheet repositories covering topics of our interest: programming and operating systems usage.

So I checked one of the existing sources [Learn X in Y Minutes](https://learnxinyminutes.com/) and it does not have Robot Framework yet. ~~Do you want me to contribute to their repository first?~~ Edited: *See my reply below*

**Comment by kalyncoose** [comment]
Upon further investigation, it looks like [Learn X in Y Minutes](https://github.com/adambard/learnxinyminutes-docs) is an abandoned repository. Only two active contributors in the past year (very few merged PRs). Also has issues with PR spam [according to the author here](https://github.com/adambard/learnxinyminutes-docs/issues/4246). I believe contributing to their repository would be worthless. So that leaves me with the option to create my own repository for Robot Framework cheats, if you agree with that idea.

**Comment by abitrolly** [comment]
@kalyncoose if you will volunteer to review at least one PR weekly, maybe guys won't mind adding you as a maintainer.

> Now, if Hacktoberfest could incentivize people to review and manage PRs it would be a different story!

**Comment by kalyncoose** [comment]
@abitrolly I think you misunderstood me, I don't want to become a maintainer - just a contributor. What do you want me to do?

**Comment by abitrolly** [comment]
@kalyncoose understood. I just proposed an option to avoid maintaining your own repository.

**Comment by kalyncoose** [comment]
@abitrolly Thanks. I'll figure it out sometime.
