### ISSUE TITLE
How to contribute a new style?

### ISSUE THREAD

**Issue by jasonlong** [chubin/cheat.sh#350]
I'd like to contribute a new style for [Nord](https://www.nordtheme.com/), but couldn't find an obvious way by looking through the code (grepped for `lovelace`, `monokai`, etc.). Could you point me in the right direction?

**Comment by nega0** [comment]
`cheat.sh` doesn't do theming itself. It uses a combination of `pygments` and direct calls to `colored`.

**Comment by jasonlong** [comment]
Ah got it, thanks.
