### ISSUE TITLE
I made a (bash & fish) shell function and alias to use cheat.sh without having to install it.

### ISSUE THREAD

**Issue by webmaster-exit-1** [chubin/cheat.sh#404]
I don't remember the situation I was in but for whatever reason I could not get to the cheat.sh documentation online. So I came up with this on the fly.

I use this everyday. Not sure if this method loses some functionality as an interactive shell, but it does work as a tldr cheatsheet. 

Bash shell alias:

```bash
# Alias script for cht.sh/cheat shell (without having to install it)
alias cheat='cheat_func() { for arg in "$@"; do curl "https://cht.sh/$arg"; done }; cheat_func'
```

Fish shell function

```sh
# Cheat Shell without having to install it
function cheat
    for arg in $argv
        curl "https://cht.sh/$arg"
    end
end
```

**Comment by lvcoi** [comment]
This is what I use for zsh

cht () {
        curl cht.sh/$@
}

**Comment by webmaster-exit-1** [comment]
Nice. I can close this or any of you can. Or maybe leave it open so the entire team can take a peak.

**Comment by webmaster-exit-1** [comment]
oh i was having an issue earlier with cht.sh and i changed it to cheat.sh. works like usual now.
