### ISSUE TITLE
Hardcoded absolute paths in code

### ISSUE THREAD

**Issue by spy16** [chubin/cheat.sh#44]
Absolute path `/home/igor/` is hard-coded in some places (files listed below) in the code base. I think it might be better if this was configurable through some mechanism like env vars etc. (Not sure if it's already possible. Did not thoroughly look into the code)

* `globals.py`
* `get_answer.py`
* `panela/panela_colors.py`
* `adapter_learnxiny.py`

**Comment by chubin** [comment]
You are 100% right. I will fix it. Thank you very much for pointing me at it.

**Comment by bglopez** [comment]
I made a pull request to hopefully help resolve this

**Comment by abitrolly** [comment]
So, can this be closed?

**Comment by chubin** [comment]
I close this one
