### ISSUE TITLE
Returns HTML instead of plain-text

### ISSUE THREAD

**Issue by warden** [chubin/cheat.sh#46]
On MacOS `curl cht.sh` returns normal HTML page for me instead of a plain text version of the cheatsheet, however `curl -q cht.sh` works fine.

**Comment by chubin** [comment]
What about `curl -A curl` ?

**Comment by warden** [comment]
```
$ curl -vI rate.sx 2>&1 | grep User-Agent
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
```

**Comment by gastlich** [comment]
same issue, same `User-Agent` value and `curl` version

**Comment by gastlich** [comment]
@chubin , cool, helped
reinstallation is needed (to get proper script instead of html from the server)

**Comment by chubin** [comment]
yes, that's true (by the way we could return the proper script for all user agents, it is a good point, thank you!)

**Comment by sesto-elemento** [comment]
Also having a problem reaching the cht.sh site via curl. Have tried it the last few days and curl just times out. Any suggestions?
