### ISSUE TITLE
yay

### ISSUE THREAD

**Issue by linux923344** [chubin/cheat.sh#47]
# Presents package selection menu
yay [Search Term]

# Prints system statistics
yay -Ps 

# Prints update list
yay -Pu              

# Cleans unneeded dependencies
yay -Yc

# Downloads PKGBUILD from ABS or AUR
yay -G               

# Generates development package DB used for devel updates.
yay -Y --gendb               

# Normal update but also check for development package updates and uses PKGBUILD modification time and not version to determine update
yay -Syu --devel --timeupdate               

# INSTALATION
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

**Comment by chubin** [comment]
Could you please add it here:
https://github.com/chubin/cheat.sheets
?

**Comment by chubin** [comment]
Done

**Comment by linux923344** [comment]
Thanks :3 Sorry ^^
