### ISSUE TITLE
Hardcoded configuration location in client.

### ISSUE THREAD

**Issue by Nunction** [chubin/cheat.sh#59]
Path ```~/.cht.sh/``` is hard-coded as the client configuration location in the client.  Would it be possible to make the client configuration location configurable. The XDG Base Directory Specification might also provide a sensible default location.

**Comment by Nunction** [comment]
Yes, an environment variable would do fine.

**Comment by chubin** [comment]
@Nunction Now you can use `CHTSH_CONF` to override the config file location.
