### ISSUE TITLE
Some ~ searches result in a 500 errors

### ISSUE THREAD

**Issue by Dagefoerde** [chubin/cheat.sh#6]
... whereas others work. 
Not working: e.g. http://cheat.sh/~php, http://cheat.sh/~go
Working: http://cheat.sh/~phpa (or meaningful searches, such as http://cheat.sh/~sql )

Seems to be a problem with searches whose keyboard directly corresponds to a namespace.

(Anyway, great work, I love this! :) )

**Comment by chubin** [comment]
@Dagefoerde Thank you very much!
