### ISSUE TITLE
Undefined name 'remove_initial_underscore' in get_answer.py

### ISSUE THREAD

**Issue by cclauss** [chubin/cheat.sh#60]
flake8 testing of https://github.com/chubin/cheat.sh on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./lib/get_answer.py:80:15: F821 undefined name 'remove_initial_underscore'
    dirname = remove_initial_underscore(dirname)
              ^
1     F821 undefined name 'remove_initial_underscore'
1
```

**Comment by chubin** [comment]
Can't find this in the code.
@cclauss What branch/repository is being tested?
