### ISSUE TITLE
Error in :intro "bash TAB-completion" install commands

### ISSUE THREAD

**Issue by doegox** [chubin/cheat.sh#63]
Replace
```
mkdir -p ~/.bash.d/cht.sh
```
by
```
mkdir -p ~/.bash.d
```

**Comment by doegox** [comment]
cf share/intro.txt
166:    {1mkdir -p ~/.bash.d/cht.sh}

**Comment by sesto-elemento** [comment]
I didn't add the function `_cht_complete` directly into ~/.bash.d/cht.sh I just appended it directly to my .bash_profile for use. However when I attempt to run `cht.sh --shell` in interactive mode I get the error `DEPENDENCY: install "rlwrap" to use cht.sh in the shell mode`. Is this a package that I need to install via home-brew in addition to the `_cht_complete` function? Help would be appreciated. Thanks

**Comment by chubin** [comment]
@doegox Thank you for reporting, Philippe!

@sesto-elemento Yes,you have to install `rlwrap` to use `cht.sh`. The brew package should be `rlwrap` too. Just use the same name.
We will make this dependency optional in the future. But for now it is mandatory (+ it is a good thing to have in system anyway).
