### ISSUE TITLE
Add cheat.sh to sublime text editor 

### ISSUE THREAD

**Issue by amaury-diallo** [chubin/cheat.sh#65]
Hello guy and thanks for this awesome tool...
Is this available on sublime text editor as plug in?
If not, how can i contribute ?
Thanks

**Comment by chubin** [comment]
Hi @amaury-diallo ! 
Do you want to contribute?
Are you a Sublime user?
Have you read about the cheat.sh-vim plugin?
Do you like it?
Should we make the same for sublime?

**Comment by chubin** [comment]
We are working on the Sublime text editor plugin, it will be released soon.
The principal developer of the plugin is @gaurav-vk.
The plugin repository is here:
https://github.com/gauravk-in/cheat.sh-sublime-plugin/
If you want to contribute, please feel free to clone the repo, change and make a PR to Gaurav.
If you have features requests, please write them here or create issues in the cheat.sh-sublime-plugin.
Any type of help is appreciated.

**Comment by amaury-diallo** [comment]
Hi, 
Yes, I'd like to contribute
I am sublime fan and user
ho, I just flew over the project and I didn't took enough time to see all features
I'll look at the cheat.sh-vim plugin properly
I'd really like to contribute but I am not professional coder yet, soooo... 
I'll fork the sublime plugin and test it 
Cia
PS: I am french, so sorry for this bad english!

**Comment by chubin** [comment]
@amaury-diallo HI Amadou!
Have you taken a look at our sublime plugin?
It is pretty good now. It supports several cool features now (though not yet all the features that are supported by our reference vim plugin).

Could you please test it and share with us your impression?

**Comment by chubin** [comment]
Initial Sublme support was added.
The puglin will be released soon.
@amaury-diallo Feel free to join development anytime.
