### ISSUE TITLE
How to change style?

### ISSUE THREAD

**Issue by okdolly** [chubin/cheat.sh#67]
I tried 
```
cht.sh python reversed a list style=xcode
cht.sh> python reverse a list style=xcode
```
They are clearly not xcode. Thanks!

**Comment by chubin** [comment]
You have to start the options list with `?`
```
python reverse a list ?style=xcode
```

**Comment by okdolly** [comment]
Is there a way to change the style once and for all? 
When I type ```cht.sh QUERY_OPTIONS="style=xcode"``` in normal mode or ``` QUERY_OPTIONS="style=xcode``` in shell mode,

I get
```
 Unknown topic.
Do you mean one of these topics maybe?
```
Thank you for your good work,chubin!
