### ISSUE TITLE
Unhighlighted search output differs in format from highlighted search output

### ISSUE THREAD

**Issue by davep** [chubin/cheat.sh#7]
I'm not sure if this is intentional or not, but I thought it worth a mention just in case...

When doing a search, with terminal highlighting on (the default), the output looks something like this:

![screen shot 2017-06-02 at 16 24 46](https://cloud.githubusercontent.com/assets/28237/26732669/4ec65366-47b0-11e7-80bb-680f00684ad7.png)

With terminal highlighting turned off ("?T" added to the URL), the output appears a little mangled in places. The initial [ in the [] that would normally appear to wrap a topic is missing, and subsequent topics appear to be missing end-of-lines before the following text. For example:

![screen shot 2017-06-02 at 16 25 02](https://cloud.githubusercontent.com/assets/28237/26732731/7ed2a26c-47b0-11e7-8959-cb8a1ed7bb2e.png)

I'd suggest that this makes for a slightly less readable output when using unhighlighted output, and potentially harder-to-parse/markup output when using unhighlighted output to feed another process.

**Comment by chubin** [comment]
You are absolutely right! Thank you for reporting
