### ISSUE TITLE
cd section fails in shell mode, returns no valid sections

### ISSUE THREAD

**Issue by phxvyper** [chubin/cheat.sh#73]
On macOS High Sierra 10.13.1

Cannot use `cd` command to change my context for queries. Queries work normally, and I can run `/:context QUERY` normally.

### Steps to repro

1. Install script locally, setup permissions
```sh
$ curl https://cht.sh/:cht.sh > /usr/local/bin/cht.sh
$ chmod +x /usr/local/bin/cht.sh
```
2. install rlwrap for shellmode
```sh
$ brew install rlwrap
```
3. launch shell mode
```sh
cht.sh --shell
```
4. attempt to cd into any section/context
```sh
cht.sh> cd go
Invalid section: go
Valid sections:
cht.sh> cd csharp
Invalid section: csharp
Valid sections:
cht.sh> cd arduino
Invalid section: arduino
Valid sections:
```

**Comment by karlosp** [comment]
I have exactly the same problem on debian installed under Windows Subsystem for Linux.

**Comment by chubin** [comment]
Yes, it is true, this was broken in this commit:
https://github.com/chubin/cheat.sh/commit/b24381c7403f956e0dfcf10417c7ebe2b8165edb
(and this was not detected by our regression tests).
I will fix this problem today. Thank you very much reporting

**Comment by chubin** [comment]
Thank you very much for reporting. The problem is fixed, please test

**Comment by karlosp** [comment]
Thanks.
It is working for me.

**Comment by rprimus** [comment]
Thu Apr 21 07:56:28 BST 2022

Hi,

Running into this on `macOS 12.3.1` (see attached animated gif):

![cht sh](https://user-images.githubusercontent.com/278414/164395002-9cf40db7-b6f0-4ff6-8ca7-cc53da485625.gif)

The problem seems to be at https://github.com/chubin/cheat.sh/blob/562875eda610b0322819def25f2d27af1bf9469a/share/cht.sh.txt#L371

The following works for me:

```
        curl -s "${CHTSH_URL}"/:list | grep ':list' | cut -d: -f1 | xargs
```

The above produces:
```
: ; curl -s https://cht.sh/:list | grep ':list' | grep ':list' | cut -d: -f1 |xargs
awk/ bash/ bf/ c/ chapel/ clojure/ cmake/ coffee/ cpp/ csharp/ d/ dart/ elisp/ elixir/ elm/ erlang/ factor/ forth/ fortran/ fsharp/ git/ go/ groovy/ haskell/ java/ js/ julia/ kotlin/ latex/ lisp/ lua/ mathematica/ matlab/ nim/ objective-c/ ocaml/ octave/ perl/ perl6/ php/ python/ python3/ r/ racket/ ruby/ rust/ solidity/ swift/ tcl/ tcsh/ vb/
```
