### ISSUE TITLE
Invalid section

### ISSUE THREAD

**Issue by pengwon** [chubin/cheat.sh#77]
hi, my english is not good, and i hope you can understand what i want to say:
![image](https://user-images.githubusercontent.com/4396692/42924326-3963e196-8b5c-11e8-8ba2-b07bff3fe07d.png)
this is my raspberry pi displayed, but i expect it should be this :
![image](https://user-images.githubusercontent.com/4396692/42924415-a6f148ca-8b5c-11e8-9a0e-b3846501923d.png)
or
![image](https://user-images.githubusercontent.com/4396692/42924430-b2d207d8-8b5c-11e8-819b-85fc1ff9920a.png)
it  seems something is wrong with 'cd' command in my cht.sh

**Comment by chubin** [comment]
Thank you very much for reporting. The problem is fixed, please test

**Comment by pengwon** [comment]
thank you for sharing. it's really very very good !
