### ISSUE TITLE
copy not working

### ISSUE THREAD

**Issue by juliuswz** [chubin/cheat.sh#78]
Ubuntu 18.04
xsel 1.2.0 

First of all I don't know if is a `xsel` or `cht.sh` client problem.

Shell mode:
```
$ cht.sh --shell
cht.sh> cd python
cht.sh/python> append file

#  python - How do you append to a file?

with open("test.txt", "a") as myfile:
    myfile.write("appended text")

cht.sh/python> copy
copy: 4 lines copied to the selection

```
The output says it was copied.
I try to paste (ctrl + v) it somewhere and I realized it was not on the clipboard.

But if I run the` xsel` command it shows the output:
```
$ xsel 

#  python - How do you append to a file?

with open("test.txt", "a") as myfile:
    myfile.write("appended text")
```

I can reproduce something like:

`$ cat /etc/hosts | xsel --clipboard`

And this works with either `ctrl + v` or the `xsel` command.

**Comment by chubin** [comment]
Please check whether it works with shift+insert or with a middle mouse click (both buttons).
Does it work for you?

**Comment by juliuswz** [comment]
No it doesn't. I'm sorry, I was not specific. When I refer to `"ctrl + v"` I mean paste in general. Either in the terminal using shift + insert or with the middle mouse as you said or ctrl + v or in any other text editor. The point is, for some reason the copy is not working here, it is not going to clipboard.

**Comment by chubin** [comment]
If you say that you can see it with `xsel` but you can't paste it, it means that it is copied to the selection buffer of X Window (PRIMARY), but not to the clipboard (CLIPBOARD).

It depends on that where you try to paste it in.
For example, if you paste it into xterm or vim running in xterm it is PRIMARY what used here,
and if you are trying to paste it indo Google Docs running inside Firefox it is CLIPBOARD
what is used here.

How could check it: 

edit cht.sh and change every occurrence of `xsel -i` with `xsel -bi`.

After that it should work as you expect.

The main question of course still remains, what should be used by default `PRIMARY` or `CLIPBOARD` or both? We currently use `PRIMARY` as it is the main selection buffer in X Window.

@juliuswz,
1) Please test, whether my conjecture is correct,
2) Please share your thoughts about the PRIMARY/CLIPBOARD controversy.

**Comment by juliuswz** [comment]
Yes, with `xsel -bi` is working as I expected. I should have looked like it was being proposed before I opened the issue, but anyway answering your question, I believe the clipboard would be useful when it was necessary for example to share with someone in some third party application, such as Slack.

**Comment by chubin** [comment]
@juliuswz Agree. I think we should use `xsel -bi` in the client. Will be fixed soon.
