### ISSUE TITLE
htop cheat: small typo

### ISSUE THREAD

**Issue by Marrakchino** [chubin/cheat.sh#8]
![image](https://user-images.githubusercontent.com/16545838/27133027-204619b2-5111-11e7-8905-f1a9f2e157d0.png)

There's a small typo at the end of `htop`'s cheat: (see also).

**Comment by chubin** [comment]
Fixed.
And I've added several new tips to this cheat sheet
(this `e also` bug is by the way not only in this cheat sheet; I will rewrite the "see also" feature soon, and then we will fix this bugs everywhere)

**Comment by chubin** [comment]
http://cheat.sh/htop
